# This is a basic workflow to help you get started with Actions

name: Download mvn

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github2
          server-password: ${{ secrets.my_secret }}
          settings-path: ${{ github.workspace }} 
        
      # Runs a single command using the runners shell
      - name: download mvn
        run: mvn dependency:copy -Dartifact=com.sherlock:herokupoc:1.0.0-202201071559 -DoutputDirectory=${{ github.workspace }} 

  build3: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github2
        server-password: ${{ secrets.my_secret }}
        settings-path: ${{ github.workspace }} 
    - name: download mvn2
      run: mvn dependency:get -DremoteRepositories=https://maven.pkg.github.com/joshjohanning-org/sherlock-heroku-poc-mvn-package/ -DgroupId="com.sherlock" -DartifactId=herokupoc -Dversion=1.0.0-202201071559 -Dtransitive=false

  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download pkg
      run: | 
        curl 'https://maven.pkg.github.com/joshjohanning-org/sherlock-heroku-poc-mvn-package/com/sherlock/herokupoc/1.0.0-202201071559/herokupoc-1.0.0-202201071559.jar' \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -L \
          -o herokupoc-1.0.0-202201071559.jar
        ls -a


  build5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "fix_world", "url": "https://maven.pkg.github.com/joshjohanning-org/sherlock-heroku-poc-mvn-package" }]'
        servers: '[{ "id": "fix_world", "username": "joshjohanning", "password": "${{ secrets.MY_SECRET }}" }]'

    - name: View settings.xml
      run: cat ~/.m2/settings.xml 
      
    - name: Install with Maven
      run: mvn install -s ~/.m2/settings.xml
      
    - name: mv
      run: mv /home/runner/.m2/repository/com/sherlock/herokupoc/1.0.0-202201071809/herokupoc-1.0.0-202201071809.jar herokupoc-1.0.0-202201071809.jar
        
    - name: ls
      run: ls -a
      

